### ISSUE TITLE
Important news?

### ISSUE THREAD

**Issue by jelockwood** [tonesto7/homebridge-smartthings#189]
See http://appleinsider.com/articles/17/06/07/apple-opens-up-homekit-development-with-software-authentication-looser-licensing

It appears it going to be possible to add HomeKit support purely in 'software' rather than as currently via a chip. This might make it possible to do more things in better ways in HomeBridge, or as also discussed previously do the reverse of HomeBridge and make HomeKit devices available to non HomeKit systems.

Obviously this is not a bug or issue but without a discussion forum for this product I thought this the next easiest way to bring it to peoples attention.

**Comment by pdlove** [comment]
This has been coming up on all of the homebridge projects. The biggest thing to note is that the HomeKit protocol used by homebridge is one that was originally leaked from Apple's development. The spec released has unveiled a couple of interesting things about the protocol but the problem is still that there aren't apps on IOS that take advantage of all of the features.
