### ISSUE TITLE
Server fails to start

### ISSUE THREAD

**Issue by custa1200** [tonesto7/homebridge-smartthings#217]
Tried to install homebridge-smartthings on my Synology using the https://hub.docker.com/r/marcoraddatz/homebridge/ container. When I add the plugin to the  container's install.sh and start the container it seems to get all the way to the end before presenting the following: 

![screenshot 2017-10-22 16 56 16](https://user-images.githubusercontent.com/161224/31858985-58ebb9ca-b750-11e7-9e30-a9f15f16f88e.png)

**Comment by rfmurphy81** [comment]
I'm getting this error, too, with some additional errors at the top (which you may be getting too).

I pulled package.json from this repository and created a file called install.sh with the following commands:

```
npm install -g homebridge
npm install -g homebridge-smartthings
```

When I run this Container, it immediately spits out the following error after loading package.json:

```
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "install"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.3
npm ERR! missing script: install
npm ERR!
npm ERR!     /root/.homebridge/npm-debug.log
```

Plus it shows:
```
*** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs>
*** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi. 
*** WARNING *** Please fix your application to use the native API of Avahi! 
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister> 
```

Then it loads the various plugins/accessories with no errors, then it shows the same exact error you posted above so I'm hopeful that whatever the fix is for you is also the fix for me, too.
