### ISSUE TITLE
app_id and token changing

### ISSUE THREAD

**Issue by Chivs** [tonesto7/homebridge-smartthings#243]
I've noticed that the app_id and access_token change every time you go into the JSON Complete API in the SmarterThings app in IOS. As new devices are not added automatically, it requires doing the above to check the box against the newly added device and saving the API settings. 
On a similar note, whenever you do access the JSON Complete API settings it does not remember previously checked devices.

Thanks.

**Comment by AndreasMenrad** [comment]
I noticed this as well a while ago. Than I realized you need to access your JSON Complete API from:
Automation -> SmartApps -> JSON Complete API

Here it shows your already selected devices and you can select more. 


Sent from my iPad

On Feb 19, 2018, at 14:35, Chivs <notifications@github.com> wrote:

I've noticed that the app_id and access_token change every time you go into the JSON Complete API in the SmarterThings app in IOS. As new devices are not added automatically, it requires doing the above to check the box against the newly added device and saving the API settings.
On a similar note, whenever you do access the JSON Complete API settings it does not remember previously checked devices.

Thanks.

**Comment by Chivs** [comment]
Thanks so much Andreas, didn't realize it was there also.

**Comment by jblakeney82** [comment]
Having the same issue but then which is the correct app ID and talking to enter into a bridge? Is it the Apple ID that just changed under smart apps or the app ID under the JsonAPI  under the automation tab? Because that ID did not change in the automation tab but the original did.  HomeKit says all of my devices are now unreachable for offline yet I can control them to the smart things app and they shall been discovered  when running the home bridge command.  Also I am pretty sure if I update the JSON file in home bridge it will rediscover all of my devices and load them into a default room and kill all of my automations

**Comment by pdlove** [comment]
On the Samsung app, goto Automation->SmartApps and select your JSON Complete API app.
This is the correct place to add the app to other devices and if you have multiples here, I suggest you delete all of them but one and include your devices on that one.
Scroll down almost all the way and tap "Config". The correct App URL, ID and Token are shown there.

**Comment by jblakeney82** [comment]
Thank you for the reply. 

Internet went down. When it came back up everything became unreachable on homkit. Verified Pi is running and so is home bridge. When running homebridge it discovers all of the devices still yet shows offline in homekit. The App ID and Token are correct and have not changed on my Config.json file in homebridge…
