### ISSUE TITLE
#250 exclude capabilities

### ISSUE THREAD

**Issue by JangoBritt** [tonesto7/homebridge-smartthings#282]
Having read the new config.json example for exclude_capabilities, I'm still not 100% certain how to get it running.

what do we enter in SmartThings_Device-ID? is that the Name of the device, or the hexadecimal ID found in homebridge.log?

Where can we find the full list of Capabilities?

For example, I have SmartThings Power sockets, which present as a Switch, and as a "Power Point"

**Comment by pdlove** [comment]
It should be the hexadecimal ID found in homebridge.log.
The capabilities list is a bit more complicated. The complete list of capabilities in Smartthings is here: https://docs.smartthings.com/en/latest/capabilities-reference.html
But not all of them are supported by HomeKit. Homebridge-Smartthings attempts to map everything that can map but unfortunately Apple's Home app really sucks and displays each accessory with a different entry for every service/capability it has.
The redesign I'm working on provides much more granularity and end-user control. I'm currently working on having the new model update in realtime and then I'm going to make a simple configuration tool to allow tweaking how specific devices map or not.

**Comment by TubadoG** [comment]
Thanks @pdlove - I'm using systemd to run the service on startup so I don't think I've got a homebridge.log - I'll see if I can get the ID from `journalctl -f -u homebridge` somehow - or perhaps I'm misunderstanding.  
In either event, your current project sounds exciting!  I've been struggling to get some SmartThings buttons to work with HomeKit, if I understand correctly, its partially because of how HomeKit implements "buttons" and/or stateless switch..  Pain in the butt really.

**Comment by dwaram983** [comment]
I'm also having an issue with this and not sure what I'm doing wrong.  I have a SmartThings Outlet and it shows up as both a Switch and an Outlet in HomeKit.  I have added the following, but see no changes in HomeKit?

"excluded_capabilities": {
  "DEVICE-ID" : [
    "Switch",
    "Power Meter",
    "Sensor",
    "Actuator",
    "Health Check",
    "Outlet"
  ]
}

Please help.  Any other examples available?
