### ISSUE TITLE
Although homebridge runs without error... do NOT see any smart devices appearing.

### ISSUE THREAD

**Issue by cvee72** [tonesto7/homebridge-smartthings#48]
Although homebridge runs without error... do NOT see any smart devices appearing.
Using ios app MyTouchHome and all devices are greyed out.

Was working fine yesterday... and i did not make any changes.
Was any new code pushed out to Smartthings via repository integration with github ?

Don't know why else it would no longer work.
Rebooted raspberrypi no improvement.

In homebridge startup i see that it identifies all my smartthing connected devices....  but its like homebridge doesn't completely start up (and gives no errors).

**Comment by pdlove** [comment]
Try this with plugin version 0.4.4. I've corrected a lot on the error handling. You'll still get the connection errors because that is all smart things being an issue.... but it shouldn't cause home bridge to crash as it has been doing.

**Comment by pdlove** [comment]
@cvee72 Let me know if this is working with 0.4.6. With your description, I can't tell if this is related to the issue most users are having.

**Comment by cvee72** [comment]
Nope.

Installed 0.4.6 but same issue.
No errors... homebridge runs and all devices are shown as found as part of
smarthings plugin.

However on IOS don't see any devices at all.

**Comment by pdlove** [comment]
Does it show your Nest accessory? Have you tried deleting your HomeKit setup in IOS yet?

**Comment by cvee72** [comment]
Yes
I've deleted homekit setup... i think.

As i mentioned earlier i have the Nest plugin installed.. but NOT configured.
I'm trying to move away from individual plugs and just use the Smartthings plugin.

I have not tried to install and configure all the individual plugins... as i assumed the Smarthings issue would be resolved hehehe.

**Comment by pdlove** [comment]
I recommend using the plugin that uses the native API for any device that has a native API because you'll get faster and potentially more reliable information.
Can I get the accessories dump HomeKit gets from home bridge? you have to start the server with "homebridge -I" for insecure mode and then get it from your web browser. For example, my homebridge server is 192.168.0.4, so I go here for the dump: http://192.168.0.4:51826/accessories
Please email it to pdlovelace@gmail.com
It will help determine if the issue is in home bridge or HomeKit.

**Comment by xtech86** [comment]
Any suggestions, I've the same issue. The dump outputs:

{"status":-70401}

**Comment by pdlove** [comment]
@tonypartridge There have been alot of updates to HomeKit and this plugin since this issue. Is it resolved now?
